### ISSUE TITLE
Typing tests appearing again

### ISSUE THREAD

**Issue by tp02000** [cooljingle/memrise-all-multiple-choice#3]
Hello, I've tried disabling tampermonkey, the github program and reloading the memrise webpage but typing tests are still appearing. I read in a previous bug report that it was due to an update, it wouldn't surprise me if it were the same thing this time. Thank you in advance

**Comment by Tolithe** [comment]
I believe they changed the URL of the app... I tried to manually fix it but got the same issue @tp02000 

https://community.memrise.com/t/moving-learning-sessions-to-app-memrise-com/55985/11

This thread discusses it but I had no fix either.

**Comment by tp02000** [comment]
Thank you for the link @Tolithe! I was able to figure it out from that forum post.

Basically, you just need to copy the following:
// @match          https://app.memrise.com/course/*/garden/*
// @match          https://app.memrise.com/garden/review/*

and paste to replace the original two //match lines in the upper section. After you have done that, click the "file" button in the top left hand corner and hit "save." Then turn off/on the extension and refresh the memrise homepage.

It is now functioning as normal for me. I hope this was of help to someone

**Comment by anthy-7** [comment]
It sure was! Thank you! :))

**Comment by Tolithe** [comment]
Hi guys, no problem! I solved it the other day too with some help from a forum user named Hombre-Sin-Nombre. Forgot to update here, but looks like top02000 got it! GL guys/gals.
